package hbm;

// Generated 19/04/2016 04:21:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Doctores generated by hbm2java
 */
public class Doctores implements java.io.Serializable {

	private String email;
	private String nombre;
	private Byte edad;
	private String password;
	private String sexo;
	private String identificacion;
	private String especialidad;
	private Set registroses = new HashSet(0);

	public Doctores() {
	}

	public Doctores(String email) {
		this.email = email;
	}

	public Doctores(String email, String nombre, Byte edad, String password,
			String sexo, String identificacion, String especialidad,
			Set registroses) {
		this.email = email;
		this.nombre = nombre;
		this.edad = edad;
		this.password = password;
		this.sexo = sexo;
		this.identificacion = identificacion;
		this.especialidad = especialidad;
		this.registroses = registroses;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getEdad() {
		return this.edad;
	}

	public void setEdad(Byte edad) {
		this.edad = edad;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Set getRegistroses() {
		return this.registroses;
	}

	public void setRegistroses(Set registroses) {
		this.registroses = registroses;
	}

}
