package hbm;

// Generated 19/04/2016 04:21:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * Registros generated by hbm2java
 */
public class Registros implements java.io.Serializable {

	private String id;
	private Doctores doctores;
	private String fechainicio;
	private String fechafin;
	private String fecharegistro;
	private Byte semana;
	private String dia;

	public Registros() {
	}

	public Registros(String id) {
		this.id = id;
	}

	public Registros(String id, Doctores doctores, String fechainicio,
			String fechafin, String fecharegistro, Byte semana, String dia) {
		this.id = id;
		this.doctores = doctores;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fecharegistro = fecharegistro;
		this.semana = semana;
		this.dia = dia;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Doctores getDoctores() {
		return this.doctores;
	}

	public void setDoctores(Doctores doctores) {
		this.doctores = doctores;
	}

	public String getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(String fechainicio) {
		this.fechainicio = fechainicio;
	}

	public String getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(String fechafin) {
		this.fechafin = fechafin;
	}

	public String getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(String fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	public Byte getSemana() {
		return this.semana;
	}

	public void setSemana(Byte semana) {
		this.semana = semana;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

}
