package hbm;

// Generated 19/04/2016 04:15:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private int id;
	private String descripcion;
	private Set profesors = new HashSet(0);
	private Set estudiantes = new HashSet(0);

	public Curso() {
	}

	public Curso(int id) {
		this.id = id;
	}

	public Curso(int id, String descripcion, Set profesors, Set estudiantes) {
		this.id = id;
		this.descripcion = descripcion;
		this.profesors = profesors;
		this.estudiantes = estudiantes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set profesors) {
		this.profesors = profesors;
	}

	public Set getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set estudiantes) {
		this.estudiantes = estudiantes;
	}

}
